### ISSUE TITLE
TypeError: Unable to serialize xxx (type: <class 'PIL.TiffImagePlugin.IFDRational'>)

### ISSUE THREAD

**Issue by jrc** [markusressel/py-image-dedup#90]
Using the Docker image `markusressel/py-image-dedup:latest`, I modified the two mountpoint paths in `docker-compose.yml` and ran `docker-compose up`. I got a bunch of errors `TypeError: Unable to serialize xxx (type: <class 'PIL.TiffImagePlugin.IFDRational'>)` like this:

```
py-image-dedup_1  | ERROR:root:({'path': '/mnt/source/0.jpg', 'signature': [0, 0, 0, 0, 1, 0, 0, -2, 0, 0, 0, -1, 1, -1, -2, -2, 0, 0, 0, -1, -2, -2, -2, -2, 0, 0, 0, 2, -1, -1, -2, -2, 0, 0, 0, 1, -1, -1, -2, -1, 0, 0, 0, 1, 1, -1, -1, -1, 0, 0, 0, -1, 0, -1, -1, -1, 0, 0, 0, 0, 1, -1, -1, -2, 0, 0, 0, -1, 0, -2, -2, 0, 0, 0, 1, 0, -2, 0, -2, -2, 2, 2, 2, 2, -1, -2, -2, 2, 2, 2, 1, 1, -1, -1, 2, 2, 2, 2, 1, 1, -1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, -1, -1, 2, -1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 1, 2, 0, -1, 2, 2, 1, 2, 2, 0, 1, 0, 2, 1, 0, 0, 2, 2, 0, -1, 0, -1, 2, 2, 2, 1, 1, 2, 1, 2, 2, -2, -2, -2, -2, -1, 1, 1, 1, -2, -2, -2, 1, -1, 1, 2, -2, -2, -2, -2, 1, -2, 2, -2, -2, -1, 1, -1, 2, 2, 1, 0, 1, -1, -2, -2, -2, 1, -2, -1, -1, -2, -2, -2, -1, -2, -2, -1, -1, -1, -1, 0, 2, 0, 1, 1, 0, 0, 1, -1, 0, 2, 0, 1, 2, -2, -2, -1, -2, 1, -2, 2, -1, -2, -1, -1, -1, 1, 1, -1, -2, -1, -2, -2, -1, -2, -1, -2, -2, 2, 2, -1, 2, -1, 2, 2, 1, 2, 0, 2, 1, 1, 2, 1, 1, -1, 1, 2, -1, 1, 1, 1, 1, 1, 1, -1, -1, 0, -1, 1, 2, 1, -1, 0, 0, 0, 1, 2, 0, 0, -1, 2, 0, 2, 0, 1, 2, -2, -2, -1, -2, -2, -2, -2, -1, 1, 1, 1, 2, -2, -1, 1, -2, 2, 2, -2, 2, -1, 2, 0, 2, 2, -2, -2, 1, -1, 1, 2, 2, -1, -1, -1, 1, -1, 2, 2, 1, -1, -1, 1, 1, 1, 2, 1, 2, -1, -1, -1, -1, 1, 1, 2, 2, -2, -2, 0, -1, 0, 1, 1, 0, 0, -1, 2, 0, 2, 0, -2, 2, -2, 2, 1, -2, 2, -2, 2, -1, 1, -1, -2, -2, -2, 1, -2, -1, 2, 0, -1, 2, 2, 1, 2, 2, -2, -2, -2, -2, -2, -2, -1, -1, -2, -2, -2, 2, -2, 1, 1, 1, -1, -1, -1, 2, 1, 2, 2, 1, -2, -2, -1, -1, 1, 2, -1, 2, -2, -1, 0, -1, 0, -1, 1, 0, 0, 2, 2, 0, 2, 0, 0, 2, -2, -2, -1, -2, -2, -2, -2, -2, 1, 2, -1, 2, 1, -1, -1, 2, 1, -2, 2, -1, 1, -2, 1, 1, -2, 1, -1, -1, -1, -1, 0, 1, 1, -1, -2, 1, -1, 1, 1, 1, -1, -2, -2, 1, -2, 1, 1, -2, -1, 1, 1, 2, 2, 2, -2, -2, -2, -1, 0, -2, 0, -2, -2, 0, 0, 0, 2, 0, 2, 0, 2, 1, -2, 2, 1, -2, 1, 2, -2, 2, 2, 1, 2, -1, 2, -2, 2, 2, -2, -1, 1, -2, 1, 2, 1, -1, -1, 0, -1, -1, 1, 1, -1, 1, -1, -1, -1, -1, -1, -2, 1, -1, -1, -1, -2, 1, -2, 1, 1, -2, 2, 2, 2, 2, -1, 2, 2, 2, 2, 2, 0, 1, 0, 2, 2, 0, 0, -2, -2, 0, -2, 0, 0, 0, -1, 2, 2, 2, 2, 0, 0, 0, -2, -2, -2, -2, -1, 0, 0, 0, -2, -1, -1, 1, -1, 0, 0, 0, 1, 1, 2, 1, 2, 0, 0, 0, -1, -1, -1, -2, -1, 0, 0, 0, 1, -1, -2, 1, -2, 0, 0, 0, 2, -2, -2, 2, 1, 0, 0, 0, -2, -2, 0, -1, 0, 0, 0, 0], 'metadata': {'path': '/mnt/source/0.jpg', 'py-image-dedup_datamodel-version': 5, 'filesize': 120968, 'file_modification_date': 1148934648.0, 'pixelcount': 272640, 'exif_data': {'ExifVersion': "b'0220'", 'ShutterSpeedValue': 5.64385986328125, 'ApertureValue': 4.33984375, 'DateTimeOriginal': '2006:05:17 19:53:58', 'DateTimeDigitized': '2006:05:17 19:53:58', 'ExposureBiasValue': 0.0, 'MaxApertureValue': 4.33984375, 'MeteringMode': 5, 'ColorSpace': 1, 'Flash': 0, 'FocalLength': 105.0, 'Make': 'Canon', 'Model': 'Canon EOS DIGITAL REBEL', 'Orientation': 1, 'YCbCrPositioning': 1, 'SensingMethod': 2, 'ExposureTime': 0.02, 'XResolution': 72.0, 'YResolution': 72.0, 'FNumber': 4.5, 'ISOSpeedRatings': 400, 'ResolutionUnit': 2, 'ExifOffset': 254, 'Software': 'QuickTime 7.1', 'DateTime': '2006:05:26 22:11:28', 'HostComputer': 'Mac OS X 10.4.6'}}, 'simple_word_0': 1149349, 'simple_word_1': 19141372, 'simple_word_2': 35611974, 'simple_word_3': 13522824, 'simple_word_4': 14554561, 'simple_word_5': 20775288, 'simple_word_6': 8741790, 'simple_word_7': 29222986, 'simple_word_8': 42574094, 'simple_word_9': 43033590, 'simple_word_10': 30292136, 'simple_word_11': 42869015, 'simple_word_12': 28651883, 'simple_word_13': 9327311, 'simple_word_14': 43044829, 'simple_word_15': 4606550, 'simple_word_16': 28859730, 'simple_word_17': 41811554, 'simple_word_18': 356231, 'simple_word_19': 14348913, 'simple_word_20': 34836237, 'simple_word_21': 10635091, 'simple_word_22': 472572, 'simple_word_23': 32949350, 'simple_word_24': 42867945, 'simple_word_25': 42924247, 'simple_word_26': 18976596, 'simple_word_27': 36961350, 'simple_word_28': 6283, 'simple_word_29': 39384954, 'simple_word_30': 30218445, 'simple_word_31': 31943833, 'simple_word_32': 14331348, 'simple_word_33': 15923789, 'simple_word_34': 36960569, 'simple_word_35': 10791109, 'simple_word_36': 24270779, 'simple_word_37': 529665, 'simple_word_38': 31886468, 'simple_word_39': 14291982, 'simple_word_40': 15569495, 'simple_word_41': 38010323, 'simple_word_42': 5560, 'simple_word_43': 12917880, 'simple_word_44': 3675836, 'simple_word_45': 32050547, 'simple_word_46': 4371750, 'simple_word_47': 14525399, 'simple_word_48': 37439498, 'simple_word_49': 33113092, 'simple_word_50': 4389140, 'simple_word_51': 1766441, 'simple_word_52': 45227, 'simple_word_53': 33067926, 'simple_word_54': 28658279, 'simple_word_55': 5075783, 'simple_word_56': 22304026, 'simple_word_57': 2303288, 'simple_word_58': 42775572, 'simple_word_59': 14379520, 'simple_word_60': 35730072, 'simple_word_61': 15169637, 'simple_word_62': 21522523, 'timestamp': datetime.datetime(2020, 11, 7, 11, 42, 43, 149502)}, TypeError("Unable to serialize 5.64385986328125 (type: <class 'PIL.TiffImagePlugin.IFDRational'>)"))
py-image-dedup_1  | Traceback (most recent call last):
py-image-dedup_1  |   File "/usr/local/lib/python3.8/site-packages/elasticsearch/serializer.py", line 120, in dumps
py-image-dedup_1  |     return json.dumps(
py-image-dedup_1  |   File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
py-image-dedup_1  |     return cls(
py-image-dedup_1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
py-image-dedup_1  |     chunks = self.iterencode(o, _one_shot=True)
py-image-dedup_1  |   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
py-image-dedup_1  |     return _iterencode(o, 0)
py-image-dedup_1  |   File "/usr/local/lib/python3.8/site-packages/elasticsearch/serializer.py", line 106, in default
py-image-dedup_1  |     raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))
py-image-dedup_1  | TypeError: Unable to serialize 5.64385986328125 (type: <class 'PIL.TiffImagePlugin.IFDRational'>)
py-image-dedup_1  | 
```

```
% docker images
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
markusressel/py-image-dedup                     latest              b5a69df15036        44 hours ago        1.3GB
docker.elastic.co/elasticsearch/elasticsearch   7.9.2               caa7a21ca06e        6 weeks ago         763MB
```

Dupe of #21?

**Comment by markusressel** [comment]
Yes that is probably related to #21. I have not yet had the time to decide how to go about this issue, but I am open to a discussion about this if you intend to open a PR.

**Comment by StephanSchuster** [comment]
Similar problems here on my Synology NAS with docker.

**Try 1:**
* Adjusted ES host and volumes in your docker-compose .yml
* `sudo docker-compose up`
Result:
```
Creating imgdedup_elasticsearch_1 ... done
Creating imgdedup_py-image-dedup_1 ... done
Attaching to imgdedup_elasticsearch_1, imgdedup_py-image-dedup_1
elasticsearch_1   | WARNING: no logs are available with the 'db' log driver
py-image-dedup_1  | WARNING: no logs are available with the 'db' log driver
```
That's it nothing more seems to work

**Try 2:**
* `sudo docker run ... docker.elastic.co/elasticsearch/elasticsearch:7.9.2`
* `sudo docker run ... markusressel/py-image-dedup:latest`
Result:
```
[ ... hundrets of lines of strange (binary) output ... ]
TypeError: Unable to serialize 0.0 (type: <class 'PIL.TiffImagePlugin.IFDRational'>)
[ ... ]
```

Try 3:
* same as in "Try 2" but with `PY_IMAGE_DEDUP_ANALYSIS_USE_EXIF_DATA=False`
Full result:
```
WARNING:matplotlib:Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ir6myqx7 because the defau
lt path (/root/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR envir
onment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support mult
iprocessing.                                                                                                          
DEBUG:py_image_dedup.util:Starting daemon...                                                                          
Starting daemon...                                                                                                    
DEBUG:py_image_dedup.util:Starting prometheus reporter...                                                             
Starting prometheus reporter...                                                                                       
DEBUG:py_image_dedup.util:Phase 1/6: Cleaning up database ...                                                         
Phase 1/6: Cleaning up database ...                                                                                   
DEBUG:py_image_dedup.util:Phase 2/6: Counting files ...                                                               
Phase 2/6: Counting files ...                                                                                         
INFO:py_image_dedup.library.progress_manager:Counting files: 100% (1/1)                                               
DEBUG:py_image_dedup.util:Phase 3/6: Analyzing files                                                                  
Phase 3/6: Analyzing files                                                                                            
INFO:py_image_dedup.library.progress_manager:Analyzing files in '/data/in': 50% (1/2)                                 
INFO:py_image_dedup.library.progress_manager:Analyzing files in '/data/in': 100% (2/2)                                
DEBUG:py_image_dedup.util:Phase 4/6: Finding duplicate files ...                                                      
Phase 4/6: Finding duplicate files ...                                                                                
INFO:py_image_dedup.library.progress_manager:Finding duplicates in '/data/in' ...: 50% (1/2)                          
INFO:py_image_dedup.library.progress_manager:Finding duplicates in '/data/in' ...: 100% (2/2)                         
DEBUG:py_image_dedup.util:Phase 5/6: Moving duplicates ...                                                            
Phase 5/6: Moving duplicates ...                                                                                      
DEBUG:py_image_dedup.util:Phase 6/6: Removing empty folders - Skipping                                                
Phase 6/6: Removing empty folders - Skipping                                                                          
DEBUG:py_image_dedup.library:Starting worker: ProcessingManager
```

Any tips for improvement in try 1 or try 2?
Any change to get this fixed as suggested in #21?
Does the output of try 3 look healthy to you?

Sorry for all those questions. I am new to docker, elasticsearch and py-image-dedup.

**Comment by markusressel** [comment]
There is really nothing you can do about the error mentioned in OP without changing the code of py-image-dedup.
The logic for ordering duplicates is currently very hardcoded, and I dislike that (which is why I created #80).
Your "Try 3" simply ignores ALL EXIF data, which might be fine depending on your use case.

**Comment by StephanSchuster** [comment]
First of all, thanks for your fast response and the effort you put in this project.

I personally think the prioritization as described [here](https://github.com/markusressel/py-image-dedup#phase-4---finding-duplicates) makes totally sense in most if not all use cases. Before enabling additional flexibility (I guess that's what #80 is about), I would therefore rather concentrate on making the "hardcoded default version" more robust, especially when it comes to EXIF (see Try 2). But that's only my newbie opinion.

Try 3 is only my fallback solution. Definitely I would prefer to also consider EXIF data when it comes to deduplication.

And just for my understanding: what's my problem with try 1? It does not seem to work in my case...

**Comment by markusressel** [comment]
> And just for my understanding: what's my problem with try 1? It does not seem to work in my case...

I don't really know. I personally don't use the compose file, so I rarely test it. Might be out of date, or something on your end :man_shrugging: .

**Comment by benmoss** [comment]
FWIW, I hit this (with the docker-compose.yml), but was able to workaround it just by disabling EXIF (`PY_IMAGE_DEDUP_ANALYSIS_USE_EXIF_DATA=False`)
