### ISSUE TITLE
v2.0.0 not published on PyPi

### ISSUE THREAD

**Issue by stormriderDE** [markusressel/py-image-dedup#99]
Hi Markus, 

unfortunately I have some trouble with ElasticSearch and can't get the code running properly. I receive this TypeError: __init__() missing 1 required positional argument: 'el_version'

```
(virtual_env) M-Air:Documents michael$ py-image-dedup deduplicate -d "/Users/michael/Desktop/bilder_test/input" -dr -esh "127.0.0.1"
Traceback (most recent call last):
  File "/Users/michael/Documents/python_workspace/virtual_env/bin/py-image-dedup", line 8, in <module>
    sys.exit(cli())
  File "/Users/michael/Documents/Python_Workspace/virtual_env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/michael/Documents/Python_Workspace/virtual_env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/michael/Documents/Python_Workspace/virtual_env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/michael/Documents/Python_Workspace/virtual_env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/michael/Documents/Python_Workspace/virtual_env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/michael/Documents/Python_Workspace/virtual_env/lib/python3.8/site-packages/py_image_dedup/cli/Main.py", line 91, in c_deduplicate
    image_signature_store=ElasticSearchStoreBackend(
  File "/Users/michael/Documents/Python_Workspace/virtual_env/lib/python3.8/site-packages/py_image_dedup/persistence/ElasticSearchStoreBackend.py", line 41, in __init__
    self._store = SignatureES(
TypeError: __init__() missing 1 required positional argument: 'el_version'
```

What can I do to solve this issue?

Thanks in advance,
Michael

**Comment by markusressel** [comment]
What elasticsearch version are you running?

**Comment by stormriderDE** [comment]
Hi Markus,

here's the snapshot of my running ElasticSearch.

![image](https://user-images.githubusercontent.com/75095358/100877836-a3f82c80-34a9-11eb-9ffa-aa5b18713e96.png)

Thanks for your guidance,
Michael

**Comment by markusressel** [comment]
Should be working with this version. How did you install py-image-dedup? Any chance you are not running the latest version?

**Comment by stormriderDE** [comment]
I've tried two approaches:
1. pip3 install py-image-dedup via terminal
2. Clone respository and pipenv install via terminal

**Comment by markusressel** [comment]
Huh, seems like v2.0.0 was not pushed to pypi properly. I guess thats causing issues for some. The "clone repo" method should work though. Check that you only have one version installed at a time, or even better, use the docker version.

**Comment by markusressel** [comment]
I have pushed v2.0.0 to PyPi now. Please report back if you still encounter the problem.

**Comment by markusressel** [comment]
closing because of inactivity

**Comment by chijiao** [comment]
same problem!
`Traceback (most recent call last):
  File "cli.py", line 94, in <module>
    cli()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 55, in c_deduplicate
    deduplicator = ImageMatchDeduplicator(interactive=True)
  File "/usr/local/lib/python3.8/dist-packages/py_image_dedup/library/deduplicator.py", line 49, in __init__
    self._persistence: ImageSignatureStore = ElasticSearchStoreBackend(
  File "/usr/local/lib/python3.8/dist-packages/py_image_dedup/persistence/elasticsearchstorebackend.py", line 73, in __init__
    self._store = SignatureES(
  File "/usr/local/lib/python3.8/dist-packages/image_match/elasticsearch_driver.py", line 47, in __init__
    super(SignatureES, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/image_match/signature_database_base.py", line 182, in __init__
    self.gis = ImageSignature(n=n_grid, crop_percentiles=crop_percentile, *signature_args, **signature_kwargs)
TypeError: __init__() got an unexpected keyword argument 'el_version'
`

`henry@DESKTOP-L25TGHU:/mnt/f$ curl 127.0.0.1:9200
{
  "name" : "DESKTOP-L25TGHU",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "aEQvTnOwQyWBUJJTIs-LCA",
  "version" : {
    "number" : "7.11.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "8ced7813d6f16d2ef30792e2fcde3e755795ee04",
    "build_date" : "2021-02-08T22:44:01.320463Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
`

installed by pip3
